"""AlertService — watches the data and generates smart alerts for Mohamed.

Alerts are generated by the hourly `generate_alerts` management command.
Each check method is idempotent: it uses get_or_create so running it
multiple times on the same day never creates duplicates.

Critical alerts are also sent via Telegram.
"""
import logging

logger = logging.getLogger(__name__)


class AlertService:
    """Generate, resolve, and push alerts."""

    @classmethod
    def generate(cls) -> list:
        """Run all alert checks. Returns list of newly created Alert objects."""
        from django.utils import timezone  # noqa: PLC0415
        from core.models import Alert  # noqa: PLC0415

        today = timezone.localdate()

        # Auto-resolve stale alerts where condition no longer applies
        cls._resolve_stale(today)

        created = []
        checks = [
            cls._check_follow_ups,
            cls._check_overdue_nodes,
            cls._check_checkin_missed,
            cls._check_readiness_drop,
            cls._check_pipeline_empty,
            cls._check_streak_broken,
            cls._check_ai_suggestions,
        ]
        for check in checks:
            try:
                result = check(today)
                if result:
                    created.extend(result if isinstance(result, list) else [result])
            except Exception:  # noqa: BLE001
                logger.exception("Alert check %s failed.", check.__name__)

        # Push critical alerts to Telegram
        critical = [a for a in created if a.priority == "critical"]
        if critical:
            cls.send_telegram_critical(critical)

        return created

    # ── Individual checks ─────────────────────────────────────────────────────

    @classmethod
    def _check_follow_ups(cls, today) -> list:
        """Pipeline opportunities with overdue follow-up dates."""
        from core.models import Alert  # noqa: PLC0415
        from pipeline.models import Opportunity  # noqa: PLC0415

        overdue = Opportunity.objects.filter(
            next_followup_date__lte=today,
            status__in=["new", "reviewing", "applied", "interview"],
        )
        created = []
        for opp in overdue:
            days_late = (today - opp.next_followup_date).days
            priority = "critical" if days_late >= 3 else "warning"
            alert, is_new = Alert.objects.get_or_create(
                alert_type="follow_up_due",
                title=f"Follow-up overdue: {opp.name}",
                date=today,
                defaults={
                    "body": (
                        f"{opp.name} ({opp.platform}) was due for follow-up "
                        f"{days_late} day{'s' if days_late != 1 else ''} ago."
                    ),
                    "priority": priority,
                    "link_url": "/business",
                },
            )
            if is_new:
                created.append(alert)
        return created

    @classmethod
    def _check_overdue_nodes(cls, today) -> list:
        """Goal nodes with a due_date in the past and not done/deferred."""
        from core.models import Alert  # noqa: PLC0415
        from goals.models import Node  # noqa: PLC0415

        overdue = Node.objects.filter(
            due_date__lt=today,
        ).exclude(status__in=["done", "deferred"])

        created = []
        for node in overdue:
            days_late = (today - node.due_date).days
            priority = "critical" if (node.priority or 3) <= 2 else "warning"
            alert, is_new = Alert.objects.get_or_create(
                alert_type="node_overdue",
                title=f"Overdue: {node.title}",
                date=today,
                defaults={
                    "body": f"Was due {days_late} day{'s' if days_late != 1 else ''} ago. Status: {node.status}.",
                    "priority": priority,
                    "link_url": "/goals",
                },
            )
            if is_new:
                created.append(alert)
        return created

    @classmethod
    def _check_checkin_missed(cls, today) -> list:
        """Morning check-in not completed by 09:00 Cairo time."""
        from django.utils import timezone  # noqa: PLC0415
        from core.models import Alert, DailyCheckIn  # noqa: PLC0415

        now_local = timezone.localtime()
        if now_local.hour < 9:
            return []  # Too early — don't alert yet

        checkin = DailyCheckIn.objects.filter(date=today).first()
        if checkin and checkin.morning_completed_at:
            return []  # Already done

        alert, is_new = Alert.objects.get_or_create(
            alert_type="checkin_missed",
            date=today,
            defaults={
                "title": "Morning check-in not done",
                "body": "Start your day with a check-in to get your AI briefing and priorities.",
                "priority": "warning",
                "link_url": "/daily",
            },
        )
        return [alert] if is_new else []

    @classmethod
    def _check_readiness_drop(cls, today) -> list:
        """Kyrgyzstan readiness score dropped more than 5 points vs yesterday."""
        import datetime  # noqa: PLC0415
        from core.models import Alert, ReadinessSnapshot  # noqa: PLC0415

        yesterday = today - datetime.timedelta(days=1)
        today_snap = ReadinessSnapshot.objects.filter(date=today).first()
        yesterday_snap = ReadinessSnapshot.objects.filter(date=yesterday).first()

        if not today_snap or not yesterday_snap:
            return []

        drop = float(yesterday_snap.total_score) - float(today_snap.total_score)
        if drop < 5:
            return []

        alert, is_new = Alert.objects.get_or_create(
            alert_type="readiness_drop",
            date=today,
            defaults={
                "title": f"Readiness score dropped {drop:.0f} points",
                "body": (
                    f"Kyrgyzstan readiness: {float(today_snap.total_score):.0f}/100 "
                    f"(was {float(yesterday_snap.total_score):.0f} yesterday). "
                    "Check which dimension dropped."
                ),
                "priority": "warning",
                "link_url": "/",
            },
        )
        return [alert] if is_new else []

    @classmethod
    def _check_pipeline_empty(cls, today) -> list:
        """No active pipeline opportunities."""
        from core.models import Alert  # noqa: PLC0415
        from pipeline.models import Opportunity  # noqa: PLC0415

        active_count = Opportunity.objects.filter(
            status__in=["new", "reviewing", "applied", "interview"],
        ).count()

        if active_count > 0:
            return []

        alert, is_new = Alert.objects.get_or_create(
            alert_type="pipeline_empty",
            date=today,
            defaults={
                "title": "Pipeline is empty",
                "body": "No active opportunities in the pipeline. Add outreach or prospect today.",
                "priority": "warning",
                "link_url": "/business",
            },
        )
        return [alert] if is_new else []

    @classmethod
    def _check_streak_broken(cls, today) -> list:
        """Routine streak broken — no blocks logged today but yesterday had some."""
        import datetime  # noqa: PLC0415
        from core.models import Alert  # noqa: PLC0415
        from schedule.models import RoutineLog  # noqa: PLC0415

        yesterday = today - datetime.timedelta(days=1)
        today_logs = RoutineLog.objects.filter(date=today).count()
        yesterday_logs = RoutineLog.objects.filter(date=yesterday, status__in=["done", "partial"]).count()

        if today_logs > 0 or yesterday_logs == 0:
            return []  # Already started today, or yesterday was also empty — no streak to break

        alert, is_new = Alert.objects.get_or_create(
            alert_type="streak_broken",
            date=today,
            defaults={
                "title": "No routine blocks logged yet today",
                "body": "Yesterday you completed blocks. Start today's routine to maintain momentum.",
                "priority": "info",
                "link_url": "/schedule",
            },
        )
        return [alert] if is_new else []

    @classmethod
    def _check_ai_suggestions(cls, today) -> list:
        """Unread AISuggestions that haven't been surfaced as alerts yet."""
        from analytics.models import AISuggestion  # noqa: PLC0415
        from core.models import Alert  # noqa: PLC0415

        unread = AISuggestion.objects.filter(
            acted_on=False,
            dismissed_at__isnull=True,
        ).order_by("-shown_at")[:3]

        created = []
        for suggestion in unread:
            alert, is_new = Alert.objects.get_or_create(
                alert_type="ai_suggestion",
                title=f"AI: {suggestion.suggestion_text[:80]}",
                date=today,
                defaults={
                    "body": suggestion.suggestion_text,
                    "priority": "info",
                    "link_url": "/analytics",
                },
            )
            if is_new:
                created.append(alert)
        return created

    # ── Resolution ─────────────────────────────────────────────────────────────

    @classmethod
    def _resolve_stale(cls, today) -> None:
        """Auto-resolve alerts where the underlying condition no longer applies."""
        from django.utils import timezone  # noqa: PLC0415
        from core.models import Alert  # noqa: PLC0415
        from pipeline.models import Opportunity  # noqa: PLC0415

        now = timezone.now()

        # Resolve pipeline_empty if opportunities now exist
        active_count = Opportunity.objects.filter(
            status__in=["new", "reviewing", "applied", "interview"],
        ).count()
        if active_count > 0:
            Alert.objects.filter(
                alert_type="pipeline_empty",
                resolved_at__isnull=True,
            ).update(resolved_at=now)

        # Resolve checkin_missed if check-in now done
        from core.models import DailyCheckIn  # noqa: PLC0415
        checkin = DailyCheckIn.objects.filter(date=today).first()
        if checkin and checkin.morning_completed_at:
            Alert.objects.filter(
                alert_type="checkin_missed",
                date=today,
                resolved_at__isnull=True,
            ).update(resolved_at=now)

    # ── Telegram push ──────────────────────────────────────────────────────────

    @classmethod
    def send_telegram_critical(cls, alerts: list) -> None:
        """Send critical alerts via Telegram and mark sent_telegram=True."""
        try:
            from core.telegram import send_message  # noqa: PLC0415

            lines = ["🚨 <b>Critical alerts</b>\n"]
            for alert in alerts:
                lines.append(f"• <b>{alert.title}</b>")
                lines.append(f"  {alert.body}")

            send_message("\n".join(lines))

            from core.models import Alert  # noqa: PLC0415
            Alert.objects.filter(id__in=[a.id for a in alerts]).update(sent_telegram=True)

        except Exception:  # noqa: BLE001
            logger.exception("Failed to send critical alerts via Telegram.")
