app = "personal-os-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  DEBUG = "false"
  TIME_ZONE = "Africa/Cairo"

[deploy]
  release_command = "python manage.py migrate --noinput"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
