# Generated by Django 5.1.15 on 2026-04-03 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('time', models.TimeField(help_text='Start time of this block (e.g. 05:00).')),
                ('label', models.CharField(help_text='Display label for this block.', max_length=255)),
                ('type', models.CharField(choices=[('spiritual', 'Spiritual'), ('health', 'Health'), ('work', 'Work'), ('marketing', 'Marketing'), ('learning', 'Learning'), ('personal', 'Personal'), ('family', 'Family')], max_length=20)),
                ('is_fixed', models.BooleanField(default=False, help_text='Fixed blocks cannot be auto-replaced by AI.')),
                ('duration_mins', models.PositiveIntegerField(help_text='Duration in minutes.')),
                ('is_adjustable', models.BooleanField(default=True, help_text='AI can fill this slot with a task.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order within the template.')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Schedule', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only one template should be active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('done', 'Done'), ('late', 'Late'), ('partial', 'Partial'), ('skipped', 'Skipped'), ('not_logged', 'Not logged')], default='not_logged', max_length=20)),
                ('actual_time', models.TimeField(blank=True, help_text='When this block was actually started.', null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='schedule.scheduleblock')),
                ('task_node', models.ForeignKey(blank=True, help_text='Task node assigned to this slot (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_logs', to='goals.node')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='schedule.scheduletemplate'),
        ),
    ]
