# Generated by Django 5.1.15 on 2026-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('block_time', models.TimeField(help_text='Start time of the routine block (e.g. 05:00).')),
                ('status', models.CharField(choices=[('done', 'Done'), ('partial', 'Partial'), ('late', 'Late'), ('skipped', 'Skipped')], max_length=10)),
                ('actual_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'block_time'],
                'unique_together': {('date', 'block_time')},
            },
        ),
    ]
