# Generated by Django 5.1.15 on 2026-04-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_add_routine_block'),
        ('schedule', '0002_routinelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Block start time, e.g. 05:00.')),
                ('label', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('spiritual', 'Spiritual'), ('health', 'Health'), ('work', 'Work'), ('personal', 'Personal'), ('family', 'Family')], default='personal', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_fixed', models.BooleanField(default=True, help_text='Fixed = user committed; flex = adjustable.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order in the schedule.')),
                ('active', models.BooleanField(default=True)),
                ('linked_node', models.ForeignKey(blank=True, help_text='Goal or project this block serves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_routine_blocks', to='goals.node')),
            ],
            options={
                'ordering': ['order', 'time'],
            },
        ),
    ]
