# Generated by Django 5.1.15 on 2026-04-08 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_node_focus_date'),
        ('schedule', '0005_routineblock_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineblock',
            name='days_of_week',
            field=models.CharField(blank=True, default='', help_text="Empty = every day. Digits 1–7 (1=Mon…7=Sun). E.g. '135' = Mon/Wed/Fri.", max_length=7),
        ),
        migrations.CreateModel(
            name='ScheduledEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The calendar date for this entry.')),
                ('time', models.TimeField(help_text='Start time of the scheduled slot.')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='How long this task is expected to take.')),
                ('label', models.CharField(blank=True, help_text='Display label — falls back to node.title when node is set.', max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, help_text='Goal task being scheduled (optional — can be a free-label entry).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_entries', to='goals.node')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
