# Generated by Django 5.1.15 on 2026-04-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_scheduled_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='first_row',
            field=models.BooleanField(blank=True, help_text='Prayed in the first row', null=True),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='prayed_in_mosque',
            field=models.BooleanField(blank=True, help_text='Prayed in the masjid', null=True),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='prayed_sunnah',
            field=models.BooleanField(blank=True, help_text='Prayed the sunnah prayers', null=True),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='takbirat_al_ihram',
            field=models.BooleanField(blank=True, help_text='Reached the opening takbeer with the imam', null=True),
        ),
    ]
