# Generated by Django 5.1.15 on 2026-04-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_prayer_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Actual minutes spent on this block.', null=True),
        ),
    ]
