# Generated by Django 5.1.15 on 2026-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_routinelog_actual_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='evening_adhkar',
            field=models.BooleanField(blank=True, help_text='Evening adhkar completed (Asr block)', null=True),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='morning_adhkar',
            field=models.BooleanField(blank=True, help_text='Morning adhkar completed (Fajr block)', null=True),
        ),
    ]
