# Generated by Django 5.1.15 on 2026-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_routinelog_add_adhkar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='salah_adhkar',
            field=models.BooleanField(blank=True, help_text='Adhkar Al-Salah completed after this prayer', null=True),
        ),
    ]
