# Generated by Django 5.1.15 on 2026-04-08 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0008_add_learning_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(choices=[('client', 'Client'), ('prospect', 'Prospect'), ('mentor', 'Mentor'), ('friend', 'Friend'), ('family', 'Family'), ('colleague', 'Colleague'), ('other', 'Other')], default='other', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('last_contact', models.DateField(blank=True, help_text='Date of most recent interaction.', null=True)),
                ('next_followup', models.DateField(blank=True, help_text='Scheduled next follow-up date.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_node', models.ForeignKey(blank=True, help_text='Optional link to a goal or project node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='goals.node')),
            ],
            options={
                'verbose_name': 'contact',
                'ordering': ['name'],
            },
        ),
    ]
