# Generated by Django 5.1.15 on 2026-04-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='crm_stage',
            field=models.CharField(blank=True, choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('active_client', 'Active Client'), ('past_client', 'Past Client'), ('partner', 'Partner'), ('employer', 'Employer')], default='', help_text='Business CRM stage for this contact.', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contacts', to='pipeline.opportunity'),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, help_text='How you met: Upwork, Referral, LinkedIn, etc.', max_length=100),
        ),
        migrations.CreateModel(
            name='ContactInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('message', 'Message'), ('note', 'Note')], max_length=20)),
                ('summary', models.TextField()),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
