# Generated by Django 5.1.15 on 2026-04-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date this entry covers (YYYY-MM-DD).', unique=True)),
                ('mood_note', models.TextField(blank=True, help_text='How am I feeling today? (free-form reflection)')),
                ('gratitude', models.TextField(blank=True, help_text='What am I grateful for today? (1–3 things)')),
                ('wins', models.TextField(blank=True, help_text='What went well or what did I accomplish today?')),
                ('tomorrow_focus', models.TextField(blank=True, help_text='What is the single most important thing for tomorrow?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'journal entry',
                'verbose_name_plural': 'journal entries',
                'ordering': ['-date'],
            },
        ),
    ]
