# Generated by Django 5.1.15 on 2026-04-03 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(help_text='Life domain (e.g. Career, Health, Spiritual).', max_length=255)),
                ('date', models.DateField(help_text='When this achievement happened.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text="Topic tag (e.g. 'outreach', 'sleep', 'goals_restructure').", max_length=255)),
                ('module', models.CharField(help_text='Which module this suggestion targets.', max_length=255)),
                ('suggestion_text', models.TextField()),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('acted_on', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-shown_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=255)),
                ('reasoning', models.TextField(help_text='Why this decision was made.')),
                ('alternatives_considered', models.TextField(blank=True, help_text='Other options that were evaluated.')),
                ('outcome', models.TextField(blank=True, help_text='What actually happened (filled in later).')),
                ('date', models.DateField(help_text='When the decision was made.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('who_involved', models.CharField(help_text='Family members involved.', max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(help_text="E.g. 'mentor', 'client', 'friend', 'colleague'.", max_length=255)),
                ('last_contact', models.DateField(blank=True, help_text='Date of last interaction.', null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('week_start', models.DateField(help_text='Monday of the review week.')),
                ('week_end', models.DateField(help_text='Sunday of the review week.')),
                ('ai_report', models.TextField(blank=True, help_text='AI-generated structured weekly report.')),
                ('personal_notes', models.TextField(blank=True, help_text="Mohamed's own reflection on the week.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True, help_text='Background, inspiration, or initial thinking.')),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('exploring', 'Exploring'), ('validated', 'Validated'), ('archived', 'Archived')], default='raw', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_goal', models.ForeignKey(blank=True, help_text='Goal this idea connects to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='goals.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('source', models.CharField(help_text='Book title, course name, resource URL, etc.', max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('key_insights', models.TextField(blank=True, help_text='Key takeaways and notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_goal', models.ForeignKey(blank=True, help_text='Goal this learning supports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learnings', to='goals.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
