# Generated by Django 5.1.15 on 2026-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weeklyreview',
            constraint=models.UniqueConstraint(fields=('week_start', 'week_end'), name='analytics_weeklyreview_unique_week_range'),
        ),
    ]
