# Generated by Django 5.1.15 on 2026-04-04 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_weeklyreview_analytics_weeklyreview_unique_week_range'),
        ('goals', '0003_goalattachmentprofile'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRetrospective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('project', 'Project'), ('opportunity', 'Opportunity')], max_length=20)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('what_worked', models.TextField(blank=True)),
                ('what_didnt', models.TextField(blank=True)),
                ('next_time', models.TextField(blank=True)),
                ('closed_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_retrospective', to='goals.node')),
                ('opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_retrospective', to='pipeline.opportunity')),
            ],
            options={
                'ordering': ['-closed_at', '-created_at'],
            },
        ),
    ]
