# Generated by Django 5.1.15 on 2026-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_projectretrospective'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='domain_hint',
            field=models.CharField(blank=True, help_text='Hub domain this idea belongs to (auto-suggested or user-set)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
