# Generated by Codex for AI Intelligence Layer US5.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_add_domain_hint_to_idea"),
        ("goals", "0005_add_routine_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionlog",
            name="enabled_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Goal this decision explicitly enabled.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enabling_decisions",
                to="goals.node",
            ),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="killed_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Goal this decision explicitly deprioritized.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="killing_decisions",
                to="goals.node",
            ),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="outcome_date",
            field=models.DateField(blank=True, help_text="When this decision should be reviewed.", null=True),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="outcome_result",
            field=models.CharField(
                blank=True,
                choices=[("right", "Right"), ("wrong", "Wrong"), ("too_early", "Too early")],
                help_text="Whether the decision proved right, wrong, or too early.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="trade_off_cost",
            field=models.TextField(blank=True, help_text="What was deliberately deprioritized by this decision."),
        ),
    ]
