# Generated by Django 5.1.15 on 2026-04-03 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('source', models.CharField(help_text='Source of income or expense category.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('EGP', 'EGP')], default='EUR', max_length=3)),
                ('is_independent', models.BooleanField(default=False, help_text='True if this income is NOT from employment (K Line Europe).')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this entry repeats monthly.')),
                ('date', models.DateField(help_text='Date of the transaction.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'finance entries',
                'ordering': ['-date'],
            },
        ),
    ]
