# Generated by Django 5.1.15 on 2026-04-06 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_incomesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('income_eur', models.DecimalField(decimal_places=2, default=0, help_text='Current monthly employment income in EUR.', max_digits=10)),
                ('income_sources_text', models.CharField(blank=True, help_text='Human-readable description of income sources.', max_length=500)),
                ('independent_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Current monthly independent income in EUR.', max_digits=10)),
                ('target_independent', models.DecimalField(decimal_places=2, default=1000, help_text='Target monthly independent income in EUR (Kyrgyzstan trigger).', max_digits=10)),
                ('monthly_expenses_egp', models.DecimalField(decimal_places=2, default=0, help_text='Monthly expenses in EGP.', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('debts', models.JSONField(blank=True, default=list, help_text='List of debt objects {name, amount_egp}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'finance summary',
                'verbose_name_plural': 'finance summaries',
            },
        ),
    ]
