# Generated by Django 5.1.15 on 2026-04-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesummary',
            name='income_egp_direct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly income received directly in EGP (e.g. local salary, freelance). Added on top of EUR income.', max_digits=12),
        ),
    ]
