# Generated by Django 5.1.15 on 2026-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_income_egp_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesummary',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=60, help_text='EUR to EGP exchange rate used for income conversion.', max_digits=7),
        ),
    ]
