# Generated by Django 5.1.15 on 2026-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the income event occurred.')),
                ('source', models.CharField(help_text='Client, deal, or source name.', max_length=255)),
                ('amount_eur', models.DecimalField(decimal_places=2, default=0, help_text='Amount in EUR (0 if non-monetary milestone).', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='financesummary',
            name='savings_current_egp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount currently saved toward the emergency fund in EGP.', max_digits=12),
        ),
        migrations.AddField(
            model_name='financesummary',
            name='savings_target_egp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Target emergency fund amount in EGP.', max_digits=12),
        ),
    ]
