# Generated by Django 5.1.15 on 2026-04-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_savings_income_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesummary',
            name='monthly_budget_egp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional monthly spending budget in EGP. Enables the budget progress bar.', max_digits=12, null=True),
        ),
    ]
