# Generated by Django 5.1.15 on 2026-04-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_monthly_budget_egp'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeentry',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Groceries'), ('housing', 'Housing & Rent'), ('transport', 'Transport'), ('utilities', 'Utilities & Bills'), ('education', 'Education'), ('children', 'Children'), ('health', 'Health'), ('debt_payment', 'Debt Payment'), ('business', 'Business'), ('savings', 'Savings'), ('other', 'Other'), ('income_employment', 'Employment Income'), ('income_independent', 'Independent Income'), ('income_other', 'Other Income')], default='', help_text='Spending or income category.', max_length=30),
        ),
        migrations.AddField(
            model_name='financesummary',
            name='category_budgets',
            field=models.JSONField(blank=True, default=dict, help_text='Monthly budget per category in EGP: {category: amount}.'),
        ),
    ]
