# Generated by Django 5.1.15 on 2026-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financeentry_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudgetPlan',
            fields=[
                ('month', models.CharField(help_text='Month in YYYY-MM format.', max_length=7, primary_key=True, serialize=False)),
                ('planned_budgets', models.JSONField(blank=True, default=dict, help_text='Planned spend per category in EGP: {category: amount}.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
    ]
