# Generated by Django 5.1.15 on 2026-04-13 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_monthlybudgetplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('creditor', models.CharField(help_text='Who is owed the money.', max_length=200)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original debt amount in EGP.', max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Current remaining balance in EGP.', max_digits=12)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, help_text='Planned monthly payment in EGP.', max_digits=10)),
                ('paid_off', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Payoff priority order (lowest = pay first).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['paid_off', 'priority', 'remaining_amount'],
            },
        ),
    ]
