# Generated by Django 5.1.15 on 2026-04-03 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Stable identifier for seeded nodes such as g1 and g2.', max_length=32, null=True, unique=True)),
                ('title', models.CharField(help_text='Name of this node.', max_length=255)),
                ('type', models.CharField(choices=[('goal', 'Goal'), ('project', 'Project'), ('task', 'Task'), ('sub_task', 'Sub-task'), ('idea', 'Idea'), ('burden', 'Burden')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('Career', 'Career'), ('Finance', 'Finance'), ('Health', 'Health'), ('Spiritual', 'Spiritual'), ('Family', 'Family'), ('Learning', 'Learning'), ('Personal', 'Personal'), ('Life', 'Life')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('available', 'Available'), ('blocked', 'Blocked'), ('done', 'Done')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Free-text notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deps', models.ManyToManyField(blank=True, help_text='Nodes this node depends on.', related_name='dependents', to='goals.node')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent node (enables nesting).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='goals.node')),
            ],
            options={
                'verbose_name_plural': 'nodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
