# Generated by Django 5.1.15 on 2026-04-04 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_node_due_date_manual_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalAttachmentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('recommended_layers', models.JSONField(blank=True, default=list, help_text='Deterministic AI-suggested support layers for this node.')),
                ('habits', models.JSONField(blank=True, default=list, help_text='Supporting habits that reinforce this goal or project.')),
                ('marketing_actions', models.JSONField(blank=True, default=list, help_text='Marketing or visibility actions attached to this node.')),
                ('process_notes', models.TextField(blank=True, help_text='Repeatable process notes that make execution easier.')),
                ('tools', models.JSONField(blank=True, default=list, help_text='Tools or systems that support the work.')),
                ('learning_path', models.JSONField(blank=True, default=list, help_text='Learning resources or milestones needed for the goal.')),
                ('supporting_people', models.JSONField(blank=True, default=list, help_text='People, mentors, or collaborators connected to this work.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_profile', to='goals.node')),
            ],
            options={
                'verbose_name': 'goal attachment profile',
                'verbose_name_plural': 'goal attachment profiles',
                'ordering': ['node__title'],
            },
        ),
    ]
