# Generated by Django 5.1.15 on 2026-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goalattachmentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='effort',
            field=models.CharField(blank=True, choices=[('15min', '15 min'), ('30min', '30 min'), ('1h', '1 hour'), ('2h', '2 hours'), ('4h', '4 hours'), ('1day', '1 day'), ('2days', '2 days'), ('1week', '1 week'), ('ongoing', 'Ongoing')], help_text='Effort estimate.', max_length=10),
        ),
        migrations.AddField(
            model_name='node',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Priority 1=Critical, 2=Important, 3=Normal, 4=Low.', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress percentage 0–100.'),
        ),
        migrations.AddField(
            model_name='node',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings.'),
        ),
        migrations.AddField(
            model_name='node',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target completion date.', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('available', 'Available'), ('blocked', 'Blocked'), ('done', 'Done'), ('deferred', 'Deferred')], default='active', max_length=20),
        ),
    ]
