# Generated by Django 5.1.15 on 2026-04-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_node_effort_node_priority_node_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_context', models.CharField(blank=True, help_text="Set to 'library' for global library items not tied to a node.", max_length=64)),
                ('type', models.CharField(choices=[('url', 'URL'), ('file', 'File'), ('snippet', 'Text snippet')], default='url', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('file', models.FileField(blank=True, upload_to='attachments/')),
                ('content', models.TextField(blank=True, help_text='For snippet type: the pasted text.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, help_text='Node this attachment belongs to. Null = library item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='goals.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
