# Generated by Django 5.1.15 on 2026-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_add_routine_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of {text, done} checklist items for lightweight sub-tracking.'),
        ),
        migrations.AddField(
            model_name='node',
            name='why',
            field=models.TextField(blank=True, help_text='The deeper motivation or reason for this goal.'),
        ),
    ]
