# Generated by Django 5.1.15 on 2026-04-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_add_why_checklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['order', '-created_at'], 'verbose_name_plural': 'nodes'},
        ),
        migrations.AddField(
            model_name='node',
            name='order',
            field=models.IntegerField(default=0, help_text='Manual sort order within the same parent group (lower = first).'),
        ),
    ]
