# Generated by Django 5.1.15 on 2026-04-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_add_node_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('book', 'Book'), ('course', 'Course'), ('article', 'Article'), ('video', 'Video'), ('podcast', 'Podcast'), ('other', 'Other')], default='book', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Done')], default='not_started', max_length=20)),
                ('progress_pct', models.IntegerField(default=0, help_text='0–100 progress percentage.')),
                ('started', models.DateField(blank=True, null=True)),
                ('finished', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_items', to='goals.node')),
            ],
            options={
                'verbose_name': 'learning item',
                'ordering': ['-updated_at'],
            },
        ),
    ]
