# Generated by Django 5.1.15 on 2026-04-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_add_learning_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the session started (UTC). Null for manual entries.', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the session ended (UTC). Null while still running.', null=True)),
                ('minutes', models.PositiveIntegerField(default=0, help_text='Duration in minutes (computed from started/ended or entered manually).')),
                ('note', models.CharField(blank=True, help_text='Optional note about what was accomplished in this session.', max_length=255)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(help_text='The node this session was logged against.', on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='goals.node')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
