# Generated by Django 5.1.15 on 2026-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_add_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='focus_date',
            field=models.DateField(blank=True, help_text="Date this node is scheduled for focused work. Set to today to surface it in Today's Focus.", null=True),
        ),
    ]
