# Generated by Django 5.1.15 on 2026-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_node_focus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='business_context',
            field=models.CharField(blank=True, choices=[('k_line', 'K Line Europe'), ('freelance', 'Freelance client'), ('own_business', 'Own business'), ('idea', 'Business idea')], default='', help_text='Which business context this node belongs to.', max_length=20),
        ),
    ]
