# Generated by Django 5.1.15 on 2026-04-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_node_business_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningitem',
            name='is_actionable',
            field=models.BooleanField(default=False, help_text='Can be converted to a goal action.'),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='review_at',
            field=models.DateField(blank=True, help_text='Next spaced-repetition review date.', null=True),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='reviewed_count',
            field=models.IntegerField(default=0, help_text='Number of times reviewed.'),
        ),
    ]
