# Generated by Django 5.1.15 on 2026-04-03 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('Upwork', 'Upwork'), ('Freelancer', 'Freelancer'), ('Referral', 'Referral'), ('Direct', 'Direct'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('applied', 'Applied'), ('won', 'Won'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('fit_score', models.IntegerField(blank=True, help_text='AI-generated fit score 0-100.', null=True)),
                ('fit_reasoning', models.TextField(blank=True, help_text='AI explanation for the fit score.')),
                ('date_found', models.DateField(help_text='When this opportunity was discovered.')),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('proposal_draft', models.TextField(blank=True, help_text='AI-drafted proposal text.')),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ['-date_found'],
            },
        ),
        migrations.CreateModel(
            name='MarketingAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='What was done.', max_length=255)),
                ('platform', models.CharField(help_text='Where it was done (LinkedIn, Upwork, email, etc.).', max_length=255)),
                ('result', models.TextField(blank=True, help_text='Outcome or response received.')),
                ('follow_up_date', models.DateField(blank=True, help_text='When to follow up.', null=True)),
                ('follow_up_done', models.BooleanField(default=False)),
                ('date', models.DateField(help_text='When this action was taken.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, help_text='Which goal this marketing action serves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_actions', to='goals.node')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_platform', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='pipeline.opportunity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
