# Generated by Django 5.1.15 on 2026-04-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_crm_stage_contact_linked_opportunity_and_more'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='job_url',
            field=models.URLField(blank=True, help_text='Link to the original job listing.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='linked_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('applied', 'Applied'), ('interview', 'Interview'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
