# Generated by Django 5.1.15 on 2026-04-10 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_crm_stage_contact_linked_opportunity_and_more'),
        ('goals', '0011_node_business_context'),
        ('pipeline', '0002_opportunity_client_name_opportunity_job_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('upwork', 'Upwork'), ('freelancer', 'Freelancer'), ('email', 'Email Outreach'), ('referral', 'Referral Network'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('profile_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_setup', 'Needs Setup'), ('inactive', 'Inactive')], default='needs_setup', max_length=20)),
                ('target_audience', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('connections', models.IntegerField(blank=True, help_text='Followers or connections count.', null=True)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.AddField(
            model_name='marketingaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('post', 'Published Post'), ('message', 'Direct Message'), ('email', 'Email'), ('comment', 'Comment / Engagement'), ('proposal', 'Proposal Submitted'), ('connection_request', 'Connection Request'), ('call', 'Call'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='marketingaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_actions', to='contacts.contact'),
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('offer', models.TextField(help_text='What is being promoted.')),
                ('target_audience', models.TextField(blank=True)),
                ('message_angle', models.TextField(blank=True, help_text='The hook or angle.')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_outreach_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to='goals.node')),
                ('channels', models.ManyToManyField(blank=True, related_name='campaigns', to='pipeline.marketingchannel')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='marketingaction',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='pipeline.marketingcampaign'),
        ),
        migrations.AddField(
            model_name='marketingaction',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='pipeline.marketingchannel'),
        ),
    ]
