# Generated by Django 5.1.15 on 2026-04-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_marketingchannel_marketingaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='ai_draft',
            field=models.TextField(blank=True, help_text='Cached AI-generated outreach message.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_outreach_at',
            field=models.DateTimeField(blank=True, help_text='When the last message was sent.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_followup_date',
            field=models.DateField(blank=True, help_text='Date when a follow-up should be sent.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='outreach_count',
            field=models.IntegerField(default=0, help_text='Total number of outreach messages sent.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='prospect_context',
            field=models.TextField(blank=True, help_text='Notes about this prospect for AI drafting.'),
        ),
    ]
