# Generated by Django 5.1.15 on 2026-04-23 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_learning_item_spaced_repetition'),
        ('pipeline', '0004_add_outreach_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='One-line sell: what it does and for whom.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('target_client', models.CharField(blank=True, help_text="Who is this for? e.g. 'Small logistics companies'", max_length=200)),
                ('pricing_model', models.CharField(choices=[('fixed', 'Fixed price'), ('hourly', 'Hourly rate'), ('retainer', 'Monthly retainer'), ('discovery', 'Discovery call → custom quote')], default='fixed', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=5)),
                ('delivery_days', models.PositiveIntegerField(blank=True, help_text='Typical engagement length in days.', null=True)),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of strings — what the client receives.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_offerings', to='goals.node')),
            ],
            options={
                'ordering': ['status', 'name'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='service_offering',
            field=models.ForeignKey(blank=True, help_text='Which service this opportunity is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='pipeline.serviceoffering'),
        ),
    ]
