# Generated by Django 5.1.15 on 2026-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_serviceoffering_opportunity_service_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(blank=True, help_text='Target date to close this opportunity.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='True = counts toward monthly recurring income metric when won.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='monthly_value_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected monthly value in EUR if recurring, or total if one-time.', max_digits=8),
        ),
    ]
