# Generated by Django 5.1.15 on 2026-04-23 14:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_opportunity_deal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, help_text="e.g. 'Perfumes retail'", max_length=200)),
                ('equity_pct', models.DecimalField(decimal_places=2, help_text='Equity percentage held, e.g. 20.00 for 20%.', max_digits=5)),
                ('status', models.CharField(choices=[('negotiating', 'Negotiating'), ('active', 'Active'), ('on_hold', 'On Hold'), ('exited', 'Exited')], default='negotiating', max_length=20)),
                ('terms_notes', models.TextField(blank=True, help_text='Agreed terms in plain text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('first_message', 'First Message Sent'), ('reply_received', 'Reply Received'), ('meeting_booked', 'Meeting Booked'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('draft_message', models.TextField(blank=True, help_text='Captured from AI draft if applicable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_steps', to='pipeline.opportunity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current_next_action', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pipeline.equitypartnership')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
