# Generated by Django 5.1.15 on 2026-04-03 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Settings', max_length=255)),
                ('eur_to_usd_rate', models.DecimalField(decimal_places=4, default=1.08, max_digits=10)),
                ('eur_to_egp_rate', models.DecimalField(decimal_places=4, default=33.5, max_digits=10)),
                ('independent_income_target_eur', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('employment_income_source_name', models.CharField(default='K Line Europe', max_length=255)),
                ('kyrgyzstan_goal_code', models.CharField(default='g1', max_length=32)),
                ('independent_income_goal_code', models.CharField(default='g2', max_length=32)),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'app settings',
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('inbox_text', models.TextField(blank=True)),
                ('blockers_text', models.TextField(blank=True)),
                ('briefing_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=64)),
                ('background', models.TextField(blank=True)),
                ('cognitive_style', models.TextField(blank=True)),
                ('family_context', models.TextField(blank=True)),
                ('life_focus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
