# Generated by Django 5.1.15 on 2026-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='energy_level',
            field=models.IntegerField(blank=True, help_text='Q3: Energy level right now 1-5.', null=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='exercise_done',
            field=models.BooleanField(blank=True, help_text='Q4: Did you exercise yesterday?', null=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='exercise_type',
            field=models.CharField(blank=True, help_text='Q4: Exercise type if done.', max_length=255),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Q1: How many hours did you sleep?', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='sleep_quality',
            field=models.IntegerField(blank=True, help_text='Q2: Sleep quality 1-5.', null=True),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='blockers_text',
            field=models.TextField(blank=True, help_text='Q7: Anything blocking you today?'),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='briefing_text',
            field=models.TextField(blank=True, help_text='AI-generated morning briefing from this check-in.'),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='inbox_text',
            field=models.TextField(blank=True, help_text='Q6: Any new thought or idea to capture?'),
        ),
    ]
