# Generated by Django 5.1.15 on 2026-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_checkin_raw_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='evening_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the evening check-in session was submitted.', null=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='evening_wins',
            field=models.TextField(blank=True, help_text='3 wins from the day (evening check-in).'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='gratitude_note',
            field=models.TextField(blank=True, help_text='Gratitude note from evening check-in.'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='mood_score',
            field=models.IntegerField(blank=True, help_text='Overall mood today 1-10 (evening).', null=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='morning_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the morning check-in session was submitted.', null=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='tomorrow_focus',
            field=models.TextField(blank=True, help_text='Top priority / focus for tomorrow.'),
        ),
    ]
