# Generated by Django 5.1.15 on 2026-04-13 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_evening_checkin_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('income_score', models.DecimalField(decimal_places=2, default=0, help_text='Max 40 — independent income vs €1,000 target', max_digits=5)),
                ('debt_score', models.DecimalField(decimal_places=2, default=0, help_text='Max 15 — total debt cleared vs 33,150 EGP baseline', max_digits=5)),
                ('pipeline_score', models.DecimalField(decimal_places=2, default=0, help_text='Max 10 — active outreach opportunities', max_digits=5)),
                ('routine_score', models.DecimalField(decimal_places=2, default=0, help_text='Max 10 — routine streak consistency', max_digits=5)),
                ('spiritual_score', models.DecimalField(decimal_places=2, default=0, help_text='Max 10 — prayer completion rate (30 days)', max_digits=5)),
                ('savings_score', models.DecimalField(decimal_places=2, default=0, help_text='Max 10 — emergency buffer vs 3 months expenses', max_digits=5)),
                ('family_score', models.DecimalField(decimal_places=2, default=0, help_text='Max 5 — family goals progress', max_digits=5)),
                ('snapshot_data', models.JSONField(blank=True, default=dict, help_text='Raw source values used in computation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
