# Generated by Django 5.1.15 on 2026-04-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_readiness_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='bad_day_mode',
            field=models.BooleanField(default=False, help_text='When on: minimal routine, no nudges, show only 3 non-negotiables.'),
        ),
    ]
