# Generated by Django 5.1.15 on 2026-04-13 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appsettings_bad_day_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('follow_up_due', 'Pipeline follow-up overdue'), ('node_overdue', 'Goal/task past due date'), ('checkin_missed', 'Morning check-in not done'), ('readiness_drop', 'Kyrgyzstan score dropped'), ('streak_broken', 'Routine streak broken'), ('pipeline_empty', 'No active pipeline opportunities'), ('ai_suggestion', 'New AI recommendation'), ('debt_milestone', 'Debt payoff milestone')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('sent_telegram', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
