# Generated by Django 5.1.15 on 2026-04-09 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('personality_type', models.CharField(blank=True, default='INTP', max_length=20)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Employment/primary income per month', max_digits=10, null=True)),
                ('income_currency', models.CharField(default='EUR', max_length=3)),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_independent_income', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Passive / semi-passive income per month', max_digits=10, null=True)),
                ('financial_target_monthly', models.DecimalField(blank=True, decimal_places=2, default=1000, help_text='Monthly independent income target', max_digits=10, null=True)),
                ('financial_target_currency', models.CharField(default='EUR', max_length=3)),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debt_currency', models.CharField(default='EGP', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='profile.userprofile')),
            ],
            options={
                'verbose_name': 'Profile Section',
                'verbose_name_plural': 'Profile Sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
