# Generated by Django 5.1.15 on 2026-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='north_star_currency',
            field=models.CharField(default='EUR', help_text='Currency symbol or code for north star display', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='north_star_label',
            field=models.CharField(blank=True, help_text="Display label for the north star metric (e.g. 'Monthly independent income')", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='north_star_target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target amount (falls back to financial_target_monthly if null)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='north_star_unit',
            field=models.CharField(default='per month', help_text="Unit label shown after the amount (e.g. 'per month')", max_length=50),
        ),
    ]
