# Generated by Django 5.1.15 on 2026-04-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_add_north_star_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(default='system', max_length=10),
        ),
    ]
