# Generated by Django 5.1.15 on 2026-04-03 13:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='One log per day.', unique=True)),
                ('sleep_hours', models.DecimalField(decimal_places=1, help_text='Hours of sleep (e.g. 7.5).', max_digits=4)),
                ('sleep_quality', models.IntegerField(help_text='Sleep quality rating 1-5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('energy_level', models.IntegerField(help_text='Energy level rating 1-5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('exercise_done', models.BooleanField(default=False)),
                ('exercise_type', models.CharField(blank=True, help_text="E.g. '30min walk', 'gym'.", max_length=255)),
                ('exercise_duration_mins', models.PositiveIntegerField(blank=True, help_text='Duration in minutes.', null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nutrition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='One mood log per day.', unique=True)),
                ('mood_score', models.IntegerField(help_text='Mood rating 1-5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SpiritualLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='One spiritual log per day.', unique=True)),
                ('fajr', models.BooleanField(default=False)),
                ('dhuhr', models.BooleanField(default=False)),
                ('asr', models.BooleanField(default=False)),
                ('maghrib', models.BooleanField(default=False)),
                ('isha', models.BooleanField(default=False)),
                ('quran_pages', models.PositiveIntegerField(default=0, help_text='Pages of Quran read today.')),
                ('dhikr_done', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(choices=[('daily', 'Daily'), ('3x_week', '3x per week'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=20)),
                ('custom_days', models.PositiveIntegerField(blank=True, help_text="Number of days per week if target is 'custom'.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, help_text='Optional linked goal node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='goals.node')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='health.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
