# Generated by Django 5.1.15 on 2026-04-13 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('name', models.CharField(help_text="Meal name, e.g. 'Oatmeal with berries'", max_length=200)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vitamins', models.JSONField(blank=True, default=dict, help_text='Vitamin %DV: keys like A, C, D, B12, folate, etc.')),
                ('minerals', models.JSONField(blank=True, default=dict, help_text='Mineral %DV: keys like iron, calcium, magnesium, zinc, etc.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['date', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('status', models.CharField(choices=[('as_planned', 'As planned'), ('ate_less', 'Ate less'), ('ate_more', 'Ate more'), ('ate_differently', 'Ate differently'), ('skipped', 'Skipped')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.OneToOneField(blank=True, help_text='The planned meal this log records against (null = unplanned meal).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='health.mealplan')),
            ],
            options={
                'ordering': ['date', 'slot'],
            },
        ),
    ]
