# Generated by Django 5.1.15 on 2026-04-13 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_add_meal_plan_and_meal_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('vitamins', models.JSONField(blank=True, default=dict)),
                ('minerals', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slot', 'name'],
            },
        ),
    ]
