# Generated by Django 5.1.15 on 2026-04-13 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_mealtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Food name (copied from FoodItem or custom)', max_length=200)),
                ('quantity_g', models.DecimalField(decimal_places=1, default=100, max_digits=7)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('food_item', models.ForeignKey(blank=True, help_text='Source food item (optional — per-100g values are snapshotted at save time).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.fooditem')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='health.mealplan')),
            ],
            options={
                'ordering': ['meal_plan', 'name'],
            },
        ),
    ]
