# Generated by Django 5.1.15 on 2026-04-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_fooditem_mealingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('protein', 'Protein'), ('grain', 'Grain & Starch'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('legume', 'Legume'), ('nut', 'Nut & Seed'), ('fat', 'Fat & Oil'), ('beverage', 'Beverage'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='cholesterol_mg_per_100g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Pre-seeded verified entry'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='minerals_per_100g',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='saturated_fat_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium_mg_per_100g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='vitamins_per_100g',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='minerals_per_100g',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='vitamins_per_100g',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
