# Generated by Django 5.1.15 on 2026-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_fooditem_options_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='grams_per_piece',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight of one piece/unit in grams (e.g. 60 for one egg).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_label',
            field=models.CharField(blank=True, help_text="Singular label for one piece, e.g. 'egg', 'banana', 'bar'.", max_length=50),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_unit',
            field=models.CharField(choices=[('g', 'Grams'), ('piece', 'Pieces / Units')], default='g', help_text='Whether this food is measured in grams or countable pieces.', max_length=10),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='grams_per_piece',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Snapshotted from FoodItem at creation time.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='quantity_pieces',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of pieces/units (null means grams-based).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='serving_label',
            field=models.CharField(blank=True, help_text="Snapshotted singular label, e.g. 'egg'.", max_length=50),
        ),
    ]
