# Generated by Django 5.1.15 on 2026-04-15 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_fooditem_grams_per_piece_fooditem_serving_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyCompositionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date of the scan or measurement.', unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Total body weight in kg.', max_digits=5)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Body fat percentage.', max_digits=5, null=True)),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Skeletal muscle mass in kg.', max_digits=5, null=True)),
                ('fat_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Total fat mass in kg.', max_digits=5, null=True)),
                ('visceral_fat_level', models.PositiveSmallIntegerField(blank=True, help_text='InBody visceral fat level (1–20 scale).', null=True)),
                ('body_water_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Total body water percentage.', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index.', max_digits=5, null=True)),
                ('metabolic_age', models.PositiveSmallIntegerField(blank=True, help_text='Metabolic age as reported by InBody.', null=True)),
                ('source', models.CharField(choices=[('inbody', 'InBody Scan'), ('manual', 'Manual Entry'), ('estimate', 'Estimate')], default='inbody', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full InBody export data for future parsing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WearableLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('source', models.CharField(choices=[('garmin', 'Garmin'), ('apple_watch', 'Apple Watch'), ('fitbit', 'Fitbit'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('active_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Total daily calories burned (TDEE).', null=True)),
                ('calories_active', models.PositiveIntegerField(blank=True, help_text='Active (non-resting) calories.', null=True)),
                ('resting_heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='Resting heart rate in bpm.', null=True)),
                ('avg_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hrv_ms', models.PositiveSmallIntegerField(blank=True, help_text='Heart Rate Variability in ms — key recovery signal.', null=True)),
                ('sleep_score', models.PositiveSmallIntegerField(blank=True, help_text='Watch-provided sleep quality score (0–100).', null=True)),
                ('spo2_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Blood oxygen saturation %.', max_digits=5, null=True)),
                ('vo2_max', models.DecimalField(blank=True, decimal_places=2, help_text='VO2 max estimate (ml/kg/min).', max_digits=5, null=True)),
                ('stress_score', models.PositiveSmallIntegerField(blank=True, help_text='Watch-provided stress score (0–100).', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full export payload for future parsing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Exercise name — stored title-cased.', max_length=255)),
                ('category', models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility')], default='compound', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the session.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('set_number', models.PositiveSmallIntegerField(default=1)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight used in kg.', max_digits=6, null=True)),
                ('duration_secs', models.PositiveIntegerField(blank=True, help_text='Duration in seconds (for timed sets).', null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, help_text='Distance in km (for cardio exercises).', max_digits=6, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='health.workoutexercise')),
            ],
            options={
                'ordering': ['exercise', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, help_text="Optional label, e.g. 'Push day A'.", max_length=255)),
                ('session_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('swimming', 'Swimming'), ('yoga', 'Yoga'), ('other', 'Other')], default='strength', max_length=20)),
                ('duration_mins', models.PositiveIntegerField(blank=True, help_text='Total session duration in minutes.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='health.healthlog')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='health.workoutsession'),
        ),
    ]
