# Generated by Django 5.1.15 on 2026-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_workout_body_composition_wearable'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='primary_muscle',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('core', 'Core'), ('glutes', 'Glutes'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves')], default='', help_text='Primary muscle group targeted by this exercise.', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, default=list, help_text='List of secondary muscle group keys.'),
        ),
    ]
