# Generated by Django 5.1.15 on 2026-04-23 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_healthgoalprofile_habit_health_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthgoalprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False),
        ),
    ]
